decks:
  - name: Women in Tech
    cards:
      - name: Sheryl Sandberg
        image_url: http://women2.com/wp-content/uploads/2013/04/Sheryl-Sandberg.jpg
        bio: 'An American businesswoman. As of August 2013, she is the chief operating officer of Facebook.'
        wiki_link: http://en.wikipedia.org/wiki/Sheryl_Sandberg
      - name: Marissa Mayer
        image_url: https://pbs.twimg.com/profile_images/323982494/marissa_new4.jpg
        bio: 'Has been President and CEO of Yahoo! since July 2012. Previously, she was a long-time executive and key spokesperson for Google.'
        wiki_link: http://en.wikipedia.org/wiki/Marissa_Mayer
      - name: Kimberly Bryant
        image_url: http://www.blackgirlscode.com/uploads/7/1/1/6/7116907/6095155.png
        bio: 'Founder Black Girls Code, Engineer~Social Entreprenuer.'
        wiki_link: http://about.me/kimberlybryant
      - name: Sarah Friar
        image_url: http://cdn.paymentssource.com/media/newspics/friar_sarah_card.jpg
        bio: 'Ex-SalesForce, current Square CFO.'
        wiki_link: http://www.crunchbase.com/person/sarah-friar
      - name: Jennifer Arguello
        image_url: https://pbs.twimg.com/profile_images/2645587037/b375b481a056c2c5d60181eeb7ea1e6a.jpeg
        bio: Ex-Mozilla and now at a VC. Passionate about bringing more Latinas into tech.
        wiki_link: http://www.jenniferarguello.com/
      - name: Lucy Sanders
        image_url: http://research.microsoft.com/en-us/collaboration/focus/cs/sandersl.jpg      
        bio: "CEO and co-founder, National Center for Women & Information Technology."
        wiki_link: http://research.microsoft.com/en-us/collaboration/focus/cs/talent_sanders.aspx
      - name: Andrea Lo
        image_url: http://blogs-images.forbes.com/women2/files/2012/12/125x125_Andrea_Lo9.jpg      
        bio: "Entrepreneur best known for co-founding the children's fundraising website Piggybackr."
        wiki_link: http://en.wikipedia.org/wiki/Andrea_Lo
  - name: Code Camp Class of 2014
    cards:
      - name: Kacey Coughlin
        image_url: http://www.kaceycoughlin.com/img/me.jpg
        bio: 'Current ICAM undergrad, Professional Dev Chair for WIC, Lead Python programmer for WalkingToolsLab @ UCSD, & Web Developer @ Peregrine Semi'
        wiki_link: http://www.kaceycoughlin.com/content/about/
      - name: Gloria Kimbwala
        image_url: https://pbs.twimg.com/profile_images/378800000614803375/ae58eec9cfc99fac2cbbf52ebab2fe81.jpeg
        bio: "Completely one of a kind nicknamed Pegasus/ Unicorn. Lover of good people,great music, and all things UK. Coolest person you'll ever meet and biggest nerd that you'll know."
        wiki_link: https://twitter.com/gkimbwala
