decks:
  - name: Women in Tech
    cards:
      - name: Sheryl Sandberg
        image_url: http://women2.com/wp-content/uploads/2013/04/Sheryl-Sandberg.jpg
        bio: 'An American businesswoman. As of August 2013, she is the chief operating officer of Facebook.'
        wiki_link: http://en.wikipedia.org/wiki/Sheryl_Sandberg
      - name: Marissa Mayer
        image_url: https://pbs.twimg.com/profile_images/323982494/marissa_new4.jpg
        bio: 'Has been President and CEO of Yahoo! since July 2012. Previously, she was a long-time executive and key spokesperson for Google.'
        wiki_link: http://en.wikipedia.org/wiki/Marissa_Mayer
      - name: Kimberly Bryant
        image_url: http://www.blackgirlscode.com/uploads/7/1/1/6/7116907/6095155.png
        bio: 'Founder Black Girls Code, Engineer~Social Entreprenuer.'
        wiki_link: http://about.me/kimberlybryant
      - name: Sarah Friar
        image_url: http://cdn.paymentssource.com/media/newspics/friar_sarah_card.jpg
        bio: 'Ex-SalesForce, current Square CFO.'
        wiki_link: http://www.crunchbase.com/person/sarah-friar
        - name: Grace Hopper
        image_url: http://upload.wikimedia.org/wikipedia/commons/a/ad/Commodore_Grace_M._Hopper%2C_USN_%28covered%29.jpg
        bio: 'A pioneer in the field, was one of the first programmers of the Harvard Mark I computer, developed the first compiler for a computer programming language.'
        wiki_link: http://en.wikipedia.org/wiki/Grace_Hopper
  - name: Code Camp Class of 2014
    cards:
      - name: Kacey Coughlin
        image_url: http://www.kaceycoughlin.com/img/me.jpg
        bio: 'Current ICAM undergrad, Professional Dev Chair for WIC, Lead Python programmer for WalkingToolsLab @ UCSD, & Web Developer @ Peregrine Semi'
        wiki_link: http://www.kaceycoughlin.com/content/about/
      - name: Gloria Kimbwala
        image_url: https://pbs.twimg.com/profile_images/378800000614803375/ae58eec9cfc99fac2cbbf52ebab2fe81.jpeg
        bio: "Completely one of a kind nicknamed Pegasus/ Unicorn. Lover of good people,great music, and all things UK. Coolest person you'll ever meet and biggest nerd that you'll know."
        wiki_link: https://twitter.com/gkimbwala
